# Generated by Django 6.1.1 on 2026-09-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('consultations', '0002_remove_diagnosis_one_primary_diagnosis_per_encounter'),
        ('patients', '0003_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='consultations.clinicalencounter'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='billing_inv_invoice_2a056e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='billing_inv_payment_f1ff3c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['service_type'], name='billing_inv_service_18e357_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['source_type', 'source_id'], name='billing_inv_source__274a89_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='billing_pay_payment_bed741_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='billing_pay_payment_715e62_idx'),
        ),
    ]
