# Generated by Django 6.1.1 on 2026-09-17 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0002_alter_patient_options_patient_next_of_kin_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-requested_date']},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-result_date']},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='laboratory.labtest'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_record', to='laboratory.labrequest'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
