# Generated by Django 6.1.1 on 2026-09-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_seed_lab_tests'),
        ('patients', '0003_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='sample_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
