# Generated by Django 6.1.1 on 2026-09-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_diagnosis_one_primary_diagnosis_per_encounter'),
        ('laboratory', '0004_alter_labrequest_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='consultations.clinicalencounter'),
        ),
    ]
