# Generated by Django 6.0.6 on 2026-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Injection', 'Injection'), ('Syrup', 'Syrup'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Medical Supply', 'Medical Supply')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('manufacturer_date', models.CharField(max_length=150)),
                ('descriptions', models.TextField(blank=True)),
            ],
        ),
    ]
