# Generated by Django 6.0.6 on 2026-08-15 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer_date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.CharField(choices=[('YES', 'Prescription Required'), ('NO', 'Over-the-Counter (OTC)')], default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('TUBE', 'Tube'), ('PACK', 'Pack')], default='TABLET', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic / Painkiller'), ('ANTIMALARIAL', 'Antimalarial'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIFUNGAL', 'Antifungal'), ('ANTIVIRAL', 'Antiviral'), ('VITAMIN', 'Vitamins & Supplements'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
