# Generated by Django 6.0.6 on 2026-08-20 10:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicinesale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('INSURANCE', 'Insurance'), ('BANK', 'Bank'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='medicinesale',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='medicinesale',
            name='medicine',
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic'), ('ANTIMALARIAL', 'Antimalarial'), ('ANTIHISTAMINE', 'Antihistamine'), ('ANTACID', 'Antacid'), ('ANTIVIRAL', 'Antiviral'), ('ANTIFUNGAL', 'Antifungal'), ('CARDIOVASCULAR', 'Cardiovascular'), ('DIABETES', 'Diabetes'), ('VITAMIN', 'Vitamin / Supplement'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('SUSPENSION', 'Suspension'), ('SOLUTION', 'Solution'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription_required',
            field=models.CharField(choices=[('YES', 'Prescription Required'), ('NO', 'Prescription Not Required')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('VIAL', 'Vial'), ('AMPOULE', 'Ampoule'), ('TUBE', 'Tube'), ('PACK', 'Pack'), ('BOX', 'Box'), ('PIECE', 'Piece')], max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='pharmacy_me_name_aa3c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['batch_number'], name='pharmacy_me_batch_n_42887c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiry_date'], name='pharmacy_me_expiry__807742_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['status'], name='pharmacy_me_status_b39fb3_idx'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.pharmacysale'),
        ),
        migrations.DeleteModel(
            name='MedicineSale',
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['sale_date'], name='pharmacy_ph_sale_da_801d95_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['patient_number'], name='pharmacy_ph_patient_0d1da5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['payment_status'], name='pharmacy_ph_payment_1bfdf7_idx'),
        ),
    ]
