# Generated by Django 6.0.6 on 2026-09-10 21:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_prescription_prescriptionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MEDICINE_CREATED', 'Medicine Created'), ('MEDICINE_UPDATED', 'Medicine Updated'), ('MEDICINE_DELETED', 'Medicine Deleted'), ('MEDICINE_DISPENSED', 'Medicine Dispensed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PRESCRIPTION_CREATED', 'Prescription Created'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('SALE_CANCELLED', 'Sale Cancelled')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='pharmacysale',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='medicine',
            name='controlled_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='pharmacysaleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pharmacysale',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='pharmacy_me_categor_6b0964_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['controlled_substance'], name='pharmacy_me_control_e94bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacysale',
            index=models.Index(fields=['payment_method'], name='pharmacy_ph_payment_83c68c_idx'),
        ),
        migrations.AddField(
            model_name='pharmacyauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pharmacyauditlog',
            index=models.Index(fields=['action'], name='pharmacy_ph_action_221e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyauditlog',
            index=models.Index(fields=['created_at'], name='pharmacy_ph_created_444cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyauditlog',
            index=models.Index(fields=['reference'], name='pharmacy_ph_referen_42420f_idx'),
        ),
    ]
