# Generated by Django 6.1.1 on 2026-09-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_pharmacyauditlog_remove_pharmacysale_paid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='unit_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='cost_price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='pharmacysaleitem',
            old_name='unit_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='pharmacysaleitem',
            old_name='cost_price',
            new_name='selling_price',
        ),
    ]
