# Generated by Django 6.1.1 on 2026-09-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_diagnosis_one_primary_diagnosis_per_encounter'),
        ('patients', '0003_alter_patient_patient_number'),
        ('pharmacy', '0008_rename_unit_price_medicine_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to='consultations.clinicalencounter'),
        ),
        migrations.AddField(
            model_name='pharmacysale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='consultations.clinicalencounter'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient'),
        ),
    ]
