# Generated by Django 6.1.1
#
# Repaired after partial application on MySQL.
#
# The previous migration attempt successfully applied some database
# operations before failing while converting prescription_required
# from YES/NO text values to a BooleanField.

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0002_remove_diagnosis_one_primary_diagnosis_per_encounter",
        ),
        (
            "patients",
            "0003_alter_patient_patient_number",
        ),
        (
            "pharmacy",
            "0009_pharmacysale_encounter_pharmacysale_patient_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # =========================================================
        # THESE DATABASE CHANGES WERE ALREADY APPLIED BEFORE THE
        # PREVIOUS MIGRATION FAILED.
        #
        # SeparateDatabaseAndState prevents Django from trying
        # to execute them a second time while still updating the
        # migration state correctly.
        # =========================================================

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="medicine",
                    name="pharmacy_me_batch_n_42887c_idx",
                ),
                migrations.RemoveIndex(
                    model_name="medicine",
                    name="pharmacy_me_control_e94bbc_idx",
                ),
                migrations.RemoveIndex(
                    model_name="pharmacyauditlog",
                    name="pharmacy_ph_action_221e1e_idx",
                ),
                migrations.RemoveIndex(
                    model_name="pharmacyauditlog",
                    name="pharmacy_ph_created_444cfc_idx",
                ),
                migrations.RemoveIndex(
                    model_name="pharmacyauditlog",
                    name="pharmacy_ph_referen_42420f_idx",
                ),
                migrations.RemoveIndex(
                    model_name="pharmacysale",
                    name="pharmacy_ph_patient_0d1da5_idx",
                ),
                migrations.RemoveIndex(
                    model_name="pharmacysale",
                    name="pharmacy_ph_payment_83c68c_idx",
                ),
                migrations.RemoveField(
                    model_name="pharmacysaleitem",
                    name="created_at",
                ),
                migrations.AddField(
                    model_name="pharmacySale".lower(),
                    name="prescription",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_sales",
                        to="pharmacy.prescription",
                    ),
                ),
                migrations.AddField(
                    model_name="pharmacysaleitem",
                    name="prescription_item",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensed_items",
                        to="pharmacy.prescriptionitem",
                    ),
                ),
                migrations.AddField(
                    model_name="prescriptionitem",
                    name="dispensed_quantity",
                    field=models.PositiveIntegerField(
                        default=0,
                    ),
                ),
            ],
        ),

        # =========================================================
        # PRESCRIPTION_REQUIRED
        #
        # Existing database values are:
        #     YES
        #     NO
        #
        # Convert them before changing the column to BOOLEAN.
        # =========================================================

        migrations.RunSQL(
            sql="""
                UPDATE pharmacy_medicine
                SET prescription_required =
                    CASE
                        WHEN UPPER(TRIM(prescription_required))
                             IN ('YES', 'TRUE', '1')
                        THEN '1'
                        ELSE '0'
                    END
            """,
            reverse_sql="""
                UPDATE pharmacy_medicine
                SET prescription_required =
                    CASE
                        WHEN prescription_required IN ('1', 'TRUE')
                        THEN 'YES'
                        ELSE 'NO'
                    END
            """,
        ),

        migrations.AlterField(
            model_name="medicine",
            name="prescription_required",
            field=models.BooleanField(default=False),
        ),

        # =========================================================
        # REMAINING MODEL CHANGES
        # =========================================================

        migrations.AlterField(
            model_name="medicine",
            name="reorder_level",
            field=models.PositiveIntegerField(default=10),
        ),

        migrations.AlterField(
            model_name="medicine",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),

        migrations.AlterField(
            model_name="medicine",
            name="unit",
            field=models.CharField(
                default="unit",
                max_length=50,
            ),
        ),

        migrations.AlterField(
            model_name="pharmacyauditlog",
            name="description",
            field=models.TextField(blank=True),
        ),

        migrations.AlterField(
            model_name="pharmacysale",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pharmacy_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AlterField(
            model_name="pharmacysale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partial"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),

        migrations.AlterField(
            model_name="pharmacysale",
            name="sale_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
            ),
        ),

        migrations.AlterField(
            model_name="pharmacysaleitem",
            name="buying_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00")
                    )
                ],
            ),
        ),

        migrations.AlterField(
            model_name="pharmacysaleitem",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.00")
                    )
                ],
            ),
        ),

        migrations.AlterField(
            model_name="pharmacysaleitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
            ),
        ),

        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),

        # =========================================================
        # NEW INDEXES
        # =========================================================

        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(
                fields=["patient"],
                name="pharmacy_ph_patient_5f2286_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(
                fields=["encounter"],
                name="pharmacy_ph_encount_b44921_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="pharmacysale",
            index=models.Index(
                fields=["prescription"],
                name="pharmacy_ph_prescri_8b9781_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="pharmacysaleitem",
            index=models.Index(
                fields=["sale"],
                name="pharmacy_ph_sale_id_f4c326_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="pharmacysaleitem",
            index=models.Index(
                fields=["medicine"],
                name="pharmacy_ph_medicin_e99c6e_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="pharmacysaleitem",
            index=models.Index(
                fields=["prescription_item"],
                name="pharmacy_ph_prescri_4634e0_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "status"],
                name="pharmacy_pr_patient_903ab2_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["encounter"],
                name="pharmacy_pr_encount_5eaae1_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescribed_at"],
                name="pharmacy_pr_prescri_117fa9_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["prescription"],
                name="pharmacy_pr_prescri_387184_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["medicine"],
                name="pharmacy_pr_medicin_fbaf33_idx",
            ),
        ),
    ]