# Generated by Django 6.1.1 on 2026-09-30 13:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_prescriptionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic'), ('ANTIMALARIAL', 'Antimalarial'), ('ANTIVIRAL', 'Antiviral'), ('ANTIFUNGAL', 'Antifungal'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTIDIABETIC', 'Antidiabetic'), ('VITAMIN', 'Vitamin'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUSPENSION', 'Suspension'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
