# Generated by Django 6.1.1 on 2026-09-21 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patient_patient_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('INPATIENT', 'Inpatient')], default='OUTPATIENT', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('encounter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('clinical_examination', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_encounters',
                'ordering': ['-encounter_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(blank=True, max_length=20)),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='consultations.clinicalencounter')),
            ],
            options={
                'db_table': 'clinical_diagnoses',
                'ordering': ['-is_primary', 'diagnosis_name'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(45)])),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='consultations.clinicalencounter')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_vital_signs',
            },
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['patient'], name='clinical_en_patient_8417dd_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['doctor'], name='clinical_en_doctor__416daa_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['status'], name='clinical_en_status_086aab_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['encounter_date'], name='clinical_en_encount_076910_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['patient', 'encounter_date'], name='clinical_en_patient_d5ea31_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['encounter'], name='clinical_di_encount_c4280f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['diagnosis_code'], name='clinical_di_diagnos_d31f6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('encounter',), name='one_primary_diagnosis_per_encounter'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['recorded_at'], name='clinical_vi_recorde_7dd4f7_idx'),
        ),
    ]
