# Generated by Django 6.1.1 on 2026-09-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosis',
            name='one_primary_diagnosis_per_encounter',
        ),
    ]
