# Generated by Django 6.1.1 on 2026-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_next_of_kin_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
